apiVersion: 1

deleteDatasources: []

datasources:
  - name: ghosts
    uid: ghosts
    orgId: 1
    type: postgres
    access: proxy
    url: ghosts-postgres:5432
    database: ghosts
    user: ghosts
    secureJsonData:
      password: 'scotty@1'
    jsonData:
      database: ghosts
      sslmode: 'disable'
    isDefault: true
