# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
deleteDatasources:

# # datasources to create
datasources:
- name: ghosts
  isDefault: true
  type: postgres
  url: ghosts-postgres:5432
  user: ghosts
  secureJsonData:
    password: scotty@1
  jsonData:
    database: ghosts
    sslmode: disable