# Copyright 2017 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

version: "3"
services: 
  pandora:
    restart: always
    container_name: ghosts-pandora
    image: dustinupdyke/ghosts-pandora
    ports:
      - "80:80"
      - "8081:8081"
      - "1935:1935"
      - "443:443"
    volumes:
      - "./app/config:/usr/src/app/config"
      - "./app/payloads:/usr/src/app/payloads"
